version: '3.4'

# docker-compose run model bash

services:
  local: 
    build: ./ #Uncomment this to rebuild
    #image:  pythonfiles_model
    stdin_open: true
    tty: true
    image: jtubespeech:v0.1.2
    #ports:
     # - 8888:8888
    #Let code run
    volumes:
      - ./:/jtubespeech
    ulimits:
      memlock: -1 # set upper limit for how much memory is locked for the container (-1 means lock as much as the container uses)
      stack: 67108864
    shm_size: 32gb # set upper limit for how much shared memory container can use